name: Integration Tests

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: integration-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: macos-14
    name: Integration Tests
    strategy:
      fail-fast: true
      matrix:
        xcode:
          - "15.3"
          - "16.0"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: make test-integration
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
